create table if not exists public.photography_images (
  id bigint generated by default as identity primary key,
  image_url text not null,
  alt_text text not null check (char_length(alt_text) between 1 and 240),
  caption text check (caption is null or char_length(caption) <= 240),
  taken_at date,
  created_at timestamptz not null default now(),
  author_id uuid not null default auth.uid() references auth.users(id)
);

alter table public.photography_images enable row level security;

drop policy if exists "Photography is public" on public.photography_images;
create policy "Photography is public"
on public.photography_images for select
using (true);

drop policy if exists "Authors can upload photographs" on public.photography_images;
create policy "Authors can upload photographs"
on public.photography_images for insert
with check (
  author_id = auth.uid()
  and exists (
    select 1 from public.blog_authors
    where blog_authors.user_id = auth.uid()
  )
);

drop policy if exists "Authors can update photographs" on public.photography_images;
create policy "Authors can update photographs"
on public.photography_images for update
using (
  author_id = auth.uid()
  and exists (
    select 1 from public.blog_authors
    where blog_authors.user_id = auth.uid()
  )
)
with check (author_id = auth.uid());

drop policy if exists "Authors can delete photographs" on public.photography_images;
create policy "Authors can delete photographs"
on public.photography_images for delete
using (
  author_id = auth.uid()
  and exists (
    select 1 from public.blog_authors
    where blog_authors.user_id = auth.uid()
  )
);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'photography',
  'photography',
  true,
  12582912,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Photography files are public" on storage.objects;
create policy "Photography files are public"
on storage.objects for select
using (bucket_id = 'photography');

drop policy if exists "Authors can upload photography files" on storage.objects;
create policy "Authors can upload photography files"
on storage.objects for insert
with check (
  bucket_id = 'photography'
  and exists (
    select 1 from public.blog_authors
    where blog_authors.user_id = auth.uid()
  )
);

drop policy if exists "Authors can update photography files" on storage.objects;
create policy "Authors can update photography files"
on storage.objects for update
using (
  bucket_id = 'photography'
  and exists (
    select 1 from public.blog_authors
    where blog_authors.user_id = auth.uid()
  )
);

drop policy if exists "Authors can delete photography files" on storage.objects;
create policy "Authors can delete photography files"
on storage.objects for delete
using (
  bucket_id = 'photography'
  and exists (
    select 1 from public.blog_authors
    where blog_authors.user_id = auth.uid()
  )
);
