create table if not exists public.music_releases (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) between 1 and 160),
  release_type text not null default 'album' check (release_type in ('album', 'single', 'ep')),
  release_date date,
  cover_url text not null,
  spotify_url text,
  apple_music_url text,
  bandcamp_url text,
  soundcloud_url text,
  created_at timestamptz not null default now(),
  author_id uuid not null default auth.uid() references auth.users(id)
);

alter table public.music_releases enable row level security;

drop policy if exists "Music releases are public" on public.music_releases;
create policy "Music releases are public"
on public.music_releases for select
using (true);

drop policy if exists "Authors can create music releases" on public.music_releases;
create policy "Authors can create music releases"
on public.music_releases for insert
with check (
  author_id = auth.uid()
  and exists (
    select 1 from public.blog_authors
    where blog_authors.user_id = auth.uid()
  )
);

drop policy if exists "Authors can update their music releases" on public.music_releases;
create policy "Authors can update their music releases"
on public.music_releases for update
using (
  author_id = auth.uid()
  and exists (
    select 1 from public.blog_authors
    where blog_authors.user_id = auth.uid()
  )
)
with check (author_id = auth.uid());

drop policy if exists "Authors can delete their music releases" on public.music_releases;
create policy "Authors can delete their music releases"
on public.music_releases for delete
using (
  author_id = auth.uid()
  and exists (
    select 1 from public.blog_authors
    where blog_authors.user_id = auth.uid()
  )
);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'music-covers',
  'music-covers',
  true,
  8388608,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Music cover artwork is public" on storage.objects;
create policy "Music cover artwork is public"
on storage.objects for select
using (bucket_id = 'music-covers');

drop policy if exists "Authors can upload music cover artwork" on storage.objects;
create policy "Authors can upload music cover artwork"
on storage.objects for insert
with check (
  bucket_id = 'music-covers'
  and exists (
    select 1 from public.blog_authors
    where blog_authors.user_id = auth.uid()
  )
);

drop policy if exists "Authors can update music cover artwork" on storage.objects;
create policy "Authors can update music cover artwork"
on storage.objects for update
using (
  bucket_id = 'music-covers'
  and exists (
    select 1 from public.blog_authors
    where blog_authors.user_id = auth.uid()
  )
);

drop policy if exists "Authors can delete music cover artwork" on storage.objects;
create policy "Authors can delete music cover artwork"
on storage.objects for delete
using (
  bucket_id = 'music-covers'
  and exists (
    select 1 from public.blog_authors
    where blog_authors.user_id = auth.uid()
  )
);
