create table public.blog_posts (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) between 1 and 160),
  content text not null check (char_length(content) > 0),
  is_draft boolean not null default false,
  published_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  author_id uuid not null default auth.uid() references auth.users(id)
);

create table public.blog_authors (
  user_id uuid primary key references auth.users(id) on delete cascade
);

create table public.music_releases (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) between 1 and 160),
  release_type text not null default 'album' check (release_type in ('album', 'single', 'ep')),
  release_date date,
  cover_url text not null,
  spotify_url text,
  apple_music_url text,
  bandcamp_url text,
  soundcloud_url text,
  created_at timestamptz not null default now(),
  author_id uuid not null default auth.uid() references auth.users(id)
);

create table public.photography_images (
  id bigint generated by default as identity primary key,
  image_url text not null,
  alt_text text check (alt_text is null or char_length(alt_text) between 1 and 240),
  caption text check (caption is null or char_length(caption) <= 240),
  taken_at date,
  created_at timestamptz not null default now(),
  author_id uuid not null default auth.uid() references auth.users(id)
);

alter table public.blog_posts enable row level security;
alter table public.blog_authors enable row level security;
alter table public.music_releases enable row level security;
alter table public.photography_images enable row level security;

create policy "Authors can read their membership"
on public.blog_authors for select
using (user_id = auth.uid());

create policy "Published posts are public"
on public.blog_posts for select
using (
  (not is_draft and published_at <= now())
  or exists (
    select 1 from public.blog_authors
    where blog_authors.user_id = auth.uid()
  )
);

create policy "Authors can create posts"
on public.blog_posts for insert
with check (
  author_id = auth.uid()
  and exists (
    select 1 from public.blog_authors
    where blog_authors.user_id = auth.uid()
  )
);

create policy "Authors can update their posts"
on public.blog_posts for update
using (
  author_id = auth.uid()
  and exists (
    select 1 from public.blog_authors
    where blog_authors.user_id = auth.uid()
  )
)
with check (author_id = auth.uid());

create policy "Authors can delete their posts"
on public.blog_posts for delete
using (
  author_id = auth.uid()
  and exists (
    select 1 from public.blog_authors
    where blog_authors.user_id = auth.uid()
  )
);

create policy "Music releases are public"
on public.music_releases for select
using (true);

create policy "Authors can create music releases"
on public.music_releases for insert
with check (
  author_id = auth.uid()
  and exists (
    select 1 from public.blog_authors
    where blog_authors.user_id = auth.uid()
  )
);

create policy "Authors can update their music releases"
on public.music_releases for update
using (
  author_id = auth.uid()
  and exists (
    select 1 from public.blog_authors
    where blog_authors.user_id = auth.uid()
  )
)
with check (author_id = auth.uid());

create policy "Authors can delete their music releases"
on public.music_releases for delete
using (
  author_id = auth.uid()
  and exists (
    select 1 from public.blog_authors
    where blog_authors.user_id = auth.uid()
  )
);

create policy "Photography is public"
on public.photography_images for select
using (true);

create policy "Authors can upload photographs"
on public.photography_images for insert
with check (
  author_id = auth.uid()
  and exists (
    select 1 from public.blog_authors
    where blog_authors.user_id = auth.uid()
  )
);

create policy "Authors can update photographs"
on public.photography_images for update
using (
  author_id = auth.uid()
  and exists (
    select 1 from public.blog_authors
    where blog_authors.user_id = auth.uid()
  )
)
with check (author_id = auth.uid());

create policy "Authors can delete photographs"
on public.photography_images for delete
using (
  author_id = auth.uid()
  and exists (
    select 1 from public.blog_authors
    where blog_authors.user_id = auth.uid()
  )
);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'music-covers',
  'music-covers',
  true,
  8388608,
  array['image/jpeg', 'image/png', 'image/webp']
);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'photography',
  'photography',
  true,
  12582912,
  array['image/jpeg', 'image/png', 'image/webp']
);

create policy "Music cover artwork is public"
on storage.objects for select
using (bucket_id = 'music-covers');

create policy "Authors can upload music cover artwork"
on storage.objects for insert
with check (
  bucket_id = 'music-covers'
  and exists (
    select 1 from public.blog_authors
    where blog_authors.user_id = auth.uid()
  )
);

create policy "Authors can update music cover artwork"
on storage.objects for update
using (
  bucket_id = 'music-covers'
  and exists (
    select 1 from public.blog_authors
    where blog_authors.user_id = auth.uid()
  )
);

create policy "Authors can delete music cover artwork"
on storage.objects for delete
using (
  bucket_id = 'music-covers'
  and exists (
    select 1 from public.blog_authors
    where blog_authors.user_id = auth.uid()
  )
);

create policy "Photography files are public"
on storage.objects for select
using (bucket_id = 'photography');

create policy "Authors can upload photography files"
on storage.objects for insert
with check (
  bucket_id = 'photography'
  and exists (
    select 1 from public.blog_authors
    where blog_authors.user_id = auth.uid()
  )
);

create policy "Authors can update photography files"
on storage.objects for update
using (
  bucket_id = 'photography'
  and exists (
    select 1 from public.blog_authors
    where blog_authors.user_id = auth.uid()
  )
);

create policy "Authors can delete photography files"
on storage.objects for delete
using (
  bucket_id = 'photography'
  and exists (
    select 1 from public.blog_authors
    where blog_authors.user_id = auth.uid()
  )
);
