create table public.blog_posts (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) between 1 and 160),
  content text not null check (char_length(content) > 0),
  published_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  author_id uuid not null default auth.uid() references auth.users(id)
);

create table public.blog_authors (
  user_id uuid primary key references auth.users(id) on delete cascade
);

alter table public.blog_posts enable row level security;
alter table public.blog_authors enable row level security;

create policy "Authors can read their membership"
on public.blog_authors for select
using (user_id = auth.uid());

create policy "Published posts are public"
on public.blog_posts for select
using (
  published_at <= now()
  or exists (
    select 1 from public.blog_authors
    where blog_authors.user_id = auth.uid()
  )
);

create policy "Authors can create posts"
on public.blog_posts for insert
with check (
  author_id = auth.uid()
  and exists (
    select 1 from public.blog_authors
    where blog_authors.user_id = auth.uid()
  )
);

create policy "Authors can update their posts"
on public.blog_posts for update
using (
  author_id = auth.uid()
  and exists (
    select 1 from public.blog_authors
    where blog_authors.user_id = auth.uid()
  )
)
with check (author_id = auth.uid());

create policy "Authors can delete their posts"
on public.blog_posts for delete
using (
  author_id = auth.uid()
  and exists (
    select 1 from public.blog_authors
    where blog_authors.user_id = auth.uid()
  )
);
